/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: khalidrahmanhanify (https://sketchfab.com/khalidrahmanhanify)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/book-animated-book-historical-book-097f8683aa5d4c9da1530d6119c20ac3
Title: Book animated book , historical book
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_60: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_64: THREE.Mesh;
    Object_66: THREE.Mesh;
    Object_68: THREE.Mesh;
    Object_70: THREE.Mesh;
    Object_72: THREE.Mesh;
    Object_74: THREE.Mesh;
    Object_76: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Animation";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/animated_book.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.599}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="pine_34"
                position={[0.065, 0.115, 0]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.09, 0.025, 1]}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.003"]}
                />
              </group>
              <group
                name="cover-r_35"
                position={[0.09, 0.025, 0]}
                scale={[0.71, 0.025, 1]}
              >
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.004"]}
                />
              </group>
              <group
                name="cover-l_36"
                position={[0.09, 0.205, 0]}
                scale={[0.71, 0.025, 1]}
              >
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name="paper_39"
                position={[0.09, 0.03, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="paper001_40"
                position={[0.09, 0.035, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper002_41"
                position={[0.09, 0.04, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper003_42"
                position={[0.09, 0.045, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper004_43"
                position={[0.09, 0.05, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper005_44"
                position={[0.09, 0.056, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper006_45"
                position={[0.09, 0.061, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper007_46"
                position={[0.09, 0.066, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper008_47"
                position={[0.09, 0.071, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper009_48"
                position={[0.09, 0.076, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper010_49"
                position={[0.09, 0.081, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper011_50"
                position={[0.09, 0.086, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper012_51"
                position={[0.09, 0.091, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper013_52"
                position={[0.09, 0.096, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper014_53"
                position={[0.09, 0.102, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper015_54"
                position={[0.09, 0.107, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper016_55"
                position={[0.09, 0.112, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials["Material.005"]}
                />
              </group>
              <group
                name="paper017_56"
                position={[0.09, 0.117, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials["Material.006"]}
                />
              </group>
              <group
                name="paper018_57"
                position={[0.09, 0.122, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper019_58"
                position={[0.09, 0.127, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper020_59"
                position={[0.09, 0.132, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper021_60"
                position={[0.09, 0.137, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper022_61"
                position={[0.09, 0.142, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper023_62"
                position={[0.09, 0.148, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper024_63"
                position={[0.09, 0.153, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper025_64"
                position={[0.09, 0.158, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper026_65"
                position={[0.09, 0.163, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper027_66"
                position={[0.09, 0.168, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper028_67"
                position={[0.09, 0.173, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper029_68"
                position={[0.09, 0.178, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper030_69"
                position={[0.09, 0.183, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper031_70"
                position={[0.09, 0.188, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_72"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper032_71"
                position={[0.09, 0.194, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_74"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper033_72"
                position={[0.088, 0.196, 0]}
                rotation={[Math.PI / 2, 0.01, 0]}
                scale={[0.71, 1, 1]}
              >
                <mesh
                  name="Object_76"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials.material_0}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/animated_book.glb");
